version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: secure_auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: secure_auth_app
    environment:
      MYSQL_URL: mysql+pymysql://user:test123@mysql_db:3306/secure_auth_db
      MYSQL_ASYNC_URL: mysql+aiomysql://user:test123@mysql_db:3306/secure_auth_db
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      GUNICORN_WORKERS: 2
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    volumes:
    - ./alembic/versions:/app/alembic/versions
    - ./static:/app/static
    - ./media:/app/media

  redis-secure-auth:
    container_name: redis-secure-auth
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  db_data:
