global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8080']  # Assuming FastAPI is running on port 3000

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scraping Prometheus itself