"""Create login otp columns

Revision ID: 54a3e6232af6
Revises: ce79ec1807a3
Create Date: 2024-11-17 14:09:14.072064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54a3e6232af6'
down_revision: Union[str, None] = 'ce79ec1807a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_otp', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('login_otp_created_at', mysql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_otp_created_at')
    op.drop_column('users', 'login_otp')
    # ### end Alembic commands ###
